spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletwise
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: change_this_secret_key
  expiration-ms: 3600000 # 1 hour

server:
  port: 8080