spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletwise
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    serialization:
      INDENT_OUTPUT: true
jwt:
  secret: mysecretkey1234567890
  expiration: 3600000 # 1 hour in ms
server:
  port: 8080