server:
  port: 8080

spring:
  application:
    name: walletwise
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/walletwise_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

# JWT Configuration
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

# OTP Configuration
otp:
  expiration: 300 # 5 minutes in seconds
  length: 6

# RabbitMQ Queue Configuration
rabbitmq:
  queue:
    transaction: transaction.queue
  exchange:
    transaction: transaction.exchange
  routing-key:
    transaction: transaction.routing.key

# Logging Configuration
logging:
  level:
    com.lee.walletwise: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE