-- Sample schema generated by JPA (simplified)
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE wallets (
    id SERIAL PRIMARY KEY,
    user_id INTEGER UNIQUE NOT NULL REFERENCES users(id),
    balance NUMERIC(19,4) NOT NULL
);

CREATE TABLE transactions (
    id SERIAL PRIMARY KEY,
    wallet_id INTEGER NOT NULL REFERENCES wallets(id),
    amount NUMERIC(19,4) NOT NULL,
    type VARCHAR(20) NOT NULL,
    description VARCHAR(255),
    timestamp TIMESTAMP NOT NULL
);